version: "3"

services:
  dnsmasq:
    build: ./dnsmasq
    volumes:
      - ./data/pxe-config/dnsmasq.conf:/etc/dnsmasq.conf
      - ./data/pxe-config/grub.cfg:/tftp/grub.cfg
      - ./data/os/EFI/BOOT/grubx64.efi:/tftp/grubx64.efi
      - ./data/os/images/pxeboot/initrd.img:/tftp/initrd.img
      - ./data/os/images/pxeboot/vmlinuz:/tftp/vmlinuz
    network_mode: host
    cap_add:
      - NET_ADMIN
  http:
    build: ./http
    volumes:
      - ./data/os:/usr/share/nginx/html/os
      - ./data/init-config/:/usr/share/nginx/html/init-config
    ports:
      - 1234:80
