all:
  vars:
    control_plane_endpoint: 192.168.1.123
    load_balancer_ip_pool:
      - 192.168.1.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.1.110, mac: '6c:4b:90:08:9b:67', disk: nvme0n1, network_interface: eth1}
    workers:
      hosts:
        metal1: {ansible_host: 192.168.1.111, mac: '6c:4b:90:21:48:2a', disk: nvme0n1, network_interface: eth1}
